forms/patient_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, RadioField, SubmitField
from wtforms.validators import DataRequired


gender_choices = (
    ("Male", "Male"),
    ("Female", "Female"),
)


class PatientForm(FlaskForm):
    FirstName = StringField("FirstName", validators=[DataRequired()])
    LastName = StringField("LastName", validators=[DataRequired()])
    DOB = DateField("Date Of Birth", validators=[DataRequired()])
    Gender = RadioField("Gender", choices=gender_choices)
    ContactNumber = StringField("ContactNumber", validators=[DataRequired()])
    Address = StringField("Address", validators=[DataRequired()])
    submit = SubmitField(label="Save")

routes/billing_routes.py
from flask import Blueprint, render_template
from sqlalchemy import insert, select
from maurs_hospital.database import db
from maurs_hospital.models import Billing

# HTML FILES
BILLING_HTML = "billing.html"

billing_records_bp = Blueprint("billing_records", __name__)


@billing_records_bp.route("/billing")
def billing():
    stmt_billing = select(Billing)
    result = db.session.execute(stmt_billing).scalars().all()

    db_billing_records = [
        {
            "BillID": billing_record.BillID,
            "PatientID": billing_record.PatientID,
            "Amount": billing_record.Amount,
            "PaymentStatus": billing_record.PaymentStatus,
        }
        for billing_record in result
    ]

    return render_template(BILLING_HTML, billing=db_billing_records)

routes/doctors_routes.py
from flask import Blueprint, render_template
from sqlalchemy import insert, select
from maurs_hospital.database import db
from maurs_hospital.models import Doctors

# HTML FILES
DOCTORS_HTML = "doctors.html"

doctors_records_bp = Blueprint("doctors", __name__)


@doctors_records_bp.route("/doctors")
def doctors():
    stmt_doctors_records = select(Doctors)
    result = db.session.execute(stmt_doctors_records).scalars().all()

    db_doctors = [
        {
            "DoctorID": doctor_record.DoctorID,
            "FirstName": doctor_record.FirstName,
            "LastName": doctor_record.LastName,
            "Specialization": doctor_record.Specialization,
            "ContactNumber": doctor_record.ContactNumber,
        }
        for doctor_record in result
    ]

    return render_template(DOCTORS_HTML, doctors=db_doctors)

routes/index_route.py
from flask import Blueprint, render_template
from sqlalchemy import insert, select
from maurs_hospital.database import db


# HTML FILES

INDEX_HTML = "index.html"
homepage_bp = Blueprint("homepage", __name__)


@homepage_bp.route("/")
def homepage():
    return render_template(INDEX_HTML)

routes/patients_routes.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from sqlalchemy import insert, select, delete, update
from maurs_hospital.database import db
from maurs_hospital.models import Patients
from maurs_hospital.forms import PatientForm
from werkzeug.datastructures import MultiDict

# HTML FILES
PATIENTS_HTML = "patients.html"

patient_bp = Blueprint("patients", __name__)


@patient_bp.route("/patients", methods=["GET", "POST"])
def patients():
    patients_form = PatientForm()

    stmt_patient_records = select(Patients)
    result = db.session.execute(stmt_patient_records).scalars().all()

    db_patients = [
        {
            "PatientID": patient_record.PatientID,
            "FirstName": patient_record.FirstName,
            "LastName": patient_record.LastName,
            "DOB": patient_record.DOB,
            "Gender": patient_record.Gender,
            "ContactNumber": patient_record.ContactNumber,
            "Address": patient_record.Address,
        }
        for patient_record in result
    ]

    # create/edit record
    if patients_form.validate_on_submit():
        form_data = request.form
        user_id_to_edit = request.args.get("user_id")

        create_new_patient_or_update_record(form_data, user_id_to_edit)

        return redirect(url_for("patients.patients"))

    # prepopulated edit record forms
    if request.args.get("edit") == "yes":
        user_id_to_edit = request.args.get("user_id")

        edit_form = prepopulate_form_fields(user_id_to_edit)
        return render_template(PATIENTS_HTML, patients=db_patients, form=edit_form)

    return render_template(PATIENTS_HTML, patients=db_patients, form=patients_form)


@patient_bp.route("/patients/<int:patientId>")
def delete_patients_record(patientId):
    patient_id_toDelete = int(patientId)

    stmt = delete(Patients).where(Patients.PatientID == patient_id_toDelete)
    db.session.execute(stmt)
    db.session.commit()

    flash('Patient record was deleted successfully')
    return redirect(url_for("patients.patients"))


def prepopulate_form_fields(user_id_to_edit:int) -> PatientForm :
    stmt_patient_records = select(Patients).where(Patients.PatientID == user_id_to_edit)
    result = db.session.execute(stmt_patient_records).scalars().all()

    db_patients = [
        {
            "PatientID": patient_record.PatientID,
            "FirstName": patient_record.FirstName,
            "LastName": patient_record.LastName,
            "DOB": patient_record.DOB,
            "Gender": patient_record.Gender,
            "ContactNumber": patient_record.ContactNumber,
            "Address": patient_record.Address,
        }
        for patient_record in result
    ]

    patients_form = PatientForm(
        formdata=MultiDict(
            [
                ("PatientID", db_patients[0]["PatientID"]),
                ("FirstName", db_patients[0]["FirstName"]),
                ("LastName", db_patients[0]["LastName"]),
                ("DOB", db_patients[0]["DOB"]),
                ("Gender", "Male" if db_patients[0]["Gender"] == "M" else "Female"),
                ("ContactNumber", db_patients[0]["ContactNumber"]),
                ("Address", db_patients[0]["Address"]),
            ]
        )
    )

    return patients_form


def create_new_patient_or_update_record(form_data: MultiDict, user_id_to_edit: int) -> None:
    current_patient_table_index = db.session.query(Patients).count()

    if user_id_to_edit is not None:
        stmt_patient_records = select(Patients).where(
            Patients.PatientID == user_id_to_edit
        )

        if db.session.execute(stmt_patient_records).first() is not None:
            stmt = (
                update(Patients)
                .where(Patients.PatientID == user_id_to_edit)
                .values(
                    (
                        user_id_to_edit,
                        form_data["FirstName"],
                        form_data["LastName"],
                        form_data["DOB"],
                        form_data["Gender"],
                        form_data["ContactNumber"],
                        form_data["Address"],
                    )
                )
            )
            db.session.execute(stmt)
            db.session.commit()

            flash('Patient record was updated successfully')
    else:

        insert_current_record_to_patient_table = insert(Patients).values(
            (
                current_patient_table_index + 1,
                form_data["FirstName"],
                form_data["LastName"],
                form_data["DOB"],
                form_data["Gender"],
                form_data["ContactNumber"],
                form_data["Address"],
            )
        )
        db.session.execute(insert_current_record_to_patient_table)
        db.session.commit()

        flash('Patient record was created successfully')

templates/appointments.html
{% extends 'index.html' %}

{% block heading %}
<div class="container text-center">
    <div class="row justify-content-center">
        <p class="h3"> Appointments  </p>
    </div>
</div> 
{% endblock %}

{% block content %}
{% if appointments %}
<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">AppointmentID</th>
                <th scope="col">PatientID</th>
                <th scope="col">DoctorID</th>
                <th scope="col">AppointmentDate</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for appt in appointments %}
            <tr>
                <td scope="row">{{appt["AppointmentID"]}}</th>
                <td>{{appt["PatientID"]}}</td>
                <td>{{appt["DoctorID"]}}</td>
                <td>{{appt["AppointmentDate"]}}</td>
                <td>{{appt["Status"]}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="card">
        <div class="card-body">
            Appointment records not available
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/billing.html
{% extends 'index.html' %}

{% block heading %} 
<div class="container text-center">
    <div class="row justify-content-center">
        <p class="h3"> Billing </p>
    </div>
</div>
{% endblock %}

{% block content %}
{% if billing %}
<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">BillID</th>
                <th scope="col">PatientID</th>
                <th scope="col">Amount</th>
                <th scope="col">PaymentStatus</th>
            </tr>
        </thead>
        <tbody>
            {% for bill in billing %}
            <tr>
                <td scope="row">{{bill["BillID"]}}</th>
                <td>{{bill["PatientID"]}}</td>
                <td>{{bill["Amount"]}}</td>
                <td>{{bill["PaymentStatus"]}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="card">
        <div class="card-body">
            Billing records not available
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/doctors.html
{% extends 'index.html' %}

{% block heading %} 
<div class="container text-center">
    <div class="row justify-content-center">
        <p class="h3"> Doctors  </p>
    </div>
</div>
{% endblock %}

{% block content %}
{% if doctors %}
<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">DoctorID</th>
                <th scope="col">FirstName</th>
                <th scope="col">LastName</th>
                <th scope="col">Specialization</th>
                <th scope="col">ContactNumber</th>
            </tr>
        </thead>
        <tbody>
            {% for doc in doctors %}
            <tr>
                <td scope="row">{{doc["DoctorID"]}}</th>
                <td>{{doc["FirstName"]}}</td>
                <td>{{doc["LastName"]}}</td>
                <td>{{doc["Specialization"]}}</td>
                <td>{{doc["ContactNumber"]}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="card">
        <div class="card-body">
            Doctors records not available
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Maurs Hospital</title>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>

    {{ font_awesome.load_js() }}

    {% block styles %}
    {{ bootstrap.load_css() }}
    {% endblock %}
</head>

<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Maurs Hospital</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('homepage.homepage')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('patients.patients')}}">Patients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('doctors.doctors')}}">Doctors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('appointments.appointments')}}">Appointments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('medical_records.medical_records')}}">Medical Records</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('billing_records.billing')}}">Billing</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div id="title">{% block heading %}{% endblock %}</div>
    <div id="content">
        {% block content %}
        <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" data-bs-interval="10000">
                    <img src="{{url_for('static', filename='care3.jfif')}}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item" data-bs-interval="2000">
                    <img src="{{url_for('static', filename='care4.jfif')}}"  class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{{url_for('static', filename='care5.jfif')}}"  class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval"
                data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval"
                data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        {% endblock %}
    </div>

</body>

</html>

templates/medical_records.html
{% extends 'index.html' %}

{% block heading %} 
<div class="container text-center">
    <div class="row justify-content-center">
        <p class="h3"> Medical Records </p>
    </div>
</div>
{% endblock %}

{% block content %}
{% if medical_records %}
<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">RecordID</th>
                <th scope="col">PatientID</th>
                <th scope="col">Diagnosis</th>
                <th scope="col">Treatment</th>
                <th scope="col">Prescription</th>
                <th scope="col">DateRecorded</th>
            </tr>
        </thead>
        <tbody>
            {% for med_record in medical_records %}
            <tr>
                <td scope="row">{{med_record["RecordID"]}}</th>
                <td>{{med_record["PatientID"]}}</td>
                <td>{{med_record["Diagnosis"]}}</td>
                <td>{{med_record["Treatment"]}}</td>
                <td>{{med_record["Prescription"]}}</td>
                <td>{{med_record["DateRecorded"]}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="card">
        <div class="card-body">
            Medical records not available
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/patients.html
{% extends 'index.html' %}
{% from 'bootstrap5/form.html' import render_form, render_field, render_form_row %}
{% from 'font_awesome.html' import render_icon, render_stacked_icons %}
{% from 'macros/alert_macro.html' import alert_message %}

{% block heading %}
<div class="container text-center">
    <div class="row justify-content-center">
        <p class="h3"> Patients</p>
    </div>
</div>
{% endblock %}


{% block content %}
<!--Render flash messages for user feedback if any-->
<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    {{alert_message(flash_message=message, alert_type='success')}}
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>

{% if form %}
<div class="container">
    {{ render_form(form)}}
</div>
{% endif %}

{% if patients %}
<div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">PatientID</th>
                <th scope="col">FirstName</th>
                <th scope="col">LastName</th>
                <th scope="col">Date Of Birth</th>
                <th scope="col">Gender</th>
                <th scope="col">ContactNumber</th>
                <th scope="col">Address</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for patient in patients %}
            <tr>
                <td scope="row">{{patient["PatientID"]}}</th>
                <td>{{patient["FirstName"]}}</td>
                <td>{{patient["LastName"]}}</td>
                <td>{{patient["DOB"]}}</td>
                <td>{{patient["Gender"]}}</td>
                <td>{{patient["ContactNumber"]}}</td>
                <td>{{patient["Address"]}}</td>
                <td>
                    <a class="patient_edit" href="{{url_for("patients.patients", edit='yes' ,
                        user_id=patient["PatientID"])}}">
                        {{ render_icon('fas fa-pen-to-square') }}
                    </a>
                    <a class="patient_delete" href="{{url_for("patients.delete_patients_record",
                        patientId=patient["PatientID"])}}">
                        {{ render_icon('fas fa-trash') }}
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="card">
        <div class="card-body">
            Patients records not available
        </div>
    </div>
</div>
{% endif %}
{% endblock %}